//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PryCertificaSIN.ServiceRecepcionComprasSIN {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://siat.impuestos.gob.bo/", ConfigurationName="ServiceRecepcionComprasSIN.ServicioFacturacion")]
    public interface ServicioFacturacion {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PryCertificaSIN.ServiceRecepcionComprasSIN.verificarComunicacionResponse verificarComunicacion(PryCertificaSIN.ServiceRecepcionComprasSIN.verificarComunicacion request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PryCertificaSIN.ServiceRecepcionComprasSIN.verificarComunicacionResponse> verificarComunicacionAsync(PryCertificaSIN.ServiceRecepcionComprasSIN.verificarComunicacion request);
        
        // CODEGEN: El parámetro 'RespuestaServicioFacturacion' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaServicioFacturacion")]
        PryCertificaSIN.ServiceRecepcionComprasSIN.validacionRecepcionPaqueteComprasResponse validacionRecepcionPaqueteCompras(PryCertificaSIN.ServiceRecepcionComprasSIN.validacionRecepcionPaqueteCompras request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PryCertificaSIN.ServiceRecepcionComprasSIN.validacionRecepcionPaqueteComprasResponse> validacionRecepcionPaqueteComprasAsync(PryCertificaSIN.ServiceRecepcionComprasSIN.validacionRecepcionPaqueteCompras request);
        
        // CODEGEN: El parámetro 'RespuestaServicioFacturacion' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaServicioFacturacion")]
        PryCertificaSIN.ServiceRecepcionComprasSIN.recepcionPaqueteComprasResponse recepcionPaqueteCompras(PryCertificaSIN.ServiceRecepcionComprasSIN.recepcionPaqueteCompras request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PryCertificaSIN.ServiceRecepcionComprasSIN.recepcionPaqueteComprasResponse> recepcionPaqueteComprasAsync(PryCertificaSIN.ServiceRecepcionComprasSIN.recepcionPaqueteCompras request);
        
        // CODEGEN: El parámetro 'RespuestaServicioFacturacion' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaServicioFacturacion")]
        PryCertificaSIN.ServiceRecepcionComprasSIN.anulacionCompraResponse anulacionCompra(PryCertificaSIN.ServiceRecepcionComprasSIN.anulacionCompra request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PryCertificaSIN.ServiceRecepcionComprasSIN.anulacionCompraResponse> anulacionCompraAsync(PryCertificaSIN.ServiceRecepcionComprasSIN.anulacionCompra request);
        
        // CODEGEN: El parámetro 'RespuestaServicioFacturacion' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaServicioFacturacion")]
        PryCertificaSIN.ServiceRecepcionComprasSIN.confirmacionComprasResponse confirmacionCompras(PryCertificaSIN.ServiceRecepcionComprasSIN.confirmacionCompras request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PryCertificaSIN.ServiceRecepcionComprasSIN.confirmacionComprasResponse> confirmacionComprasAsync(PryCertificaSIN.ServiceRecepcionComprasSIN.confirmacionCompras request);
        
        // CODEGEN: El parámetro 'RespuestaServicioFacturacion' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaServicioFacturacion")]
        PryCertificaSIN.ServiceRecepcionComprasSIN.consultaComprasResponse consultaCompras(PryCertificaSIN.ServiceRecepcionComprasSIN.consultaCompras request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PryCertificaSIN.ServiceRecepcionComprasSIN.consultaComprasResponse> consultaComprasAsync(PryCertificaSIN.ServiceRecepcionComprasSIN.consultaCompras request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaComunicacion : modelDto {
        
        private mensajeServicio[] mensajesListField;
        
        private bool transaccionField;
        
        private bool transaccionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensajesList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public mensajeServicio[] mensajesList {
            get {
                return this.mensajesListField;
            }
            set {
                this.mensajesListField = value;
                this.RaisePropertyChanged("mensajesList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool transaccion {
            get {
                return this.transaccionField;
            }
            set {
                this.transaccionField = value;
                this.RaisePropertyChanged("transaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transaccionSpecified {
            get {
                return this.transaccionFieldSpecified;
            }
            set {
                this.transaccionFieldSpecified = value;
                this.RaisePropertyChanged("transaccionSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mensajeRecepcion))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class mensajeServicio : modelDto {
        
        private int codigoField;
        
        private bool codigoFieldSpecified;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoSpecified {
            get {
                return this.codigoFieldSpecified;
            }
            set {
                this.codigoFieldSpecified = value;
                this.RaisePropertyChanged("codigoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaConsultaCompras))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudCompras))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudConsultaCompras))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudAnulacionCompra))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionCompras))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudValidacionRecepcionCompras))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mensajeServicio))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mensajeRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaComunicacion))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public abstract partial class modelDto : model {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(modelDto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaConsultaCompras))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudCompras))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudConsultaCompras))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudAnulacionCompra))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionCompras))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudValidacionRecepcionCompras))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mensajeServicio))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mensajeRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaComunicacion))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public abstract partial class model : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaConsultaCompras : modelDto {
        
        private byte[] archivoField;
        
        private mensajeRecepcion[] mensajesListField;
        
        private bool transaccionField;
        
        private bool transaccionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] archivo {
            get {
                return this.archivoField;
            }
            set {
                this.archivoField = value;
                this.RaisePropertyChanged("archivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensajesList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public mensajeRecepcion[] mensajesList {
            get {
                return this.mensajesListField;
            }
            set {
                this.mensajesListField = value;
                this.RaisePropertyChanged("mensajesList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool transaccion {
            get {
                return this.transaccionField;
            }
            set {
                this.transaccionField = value;
                this.RaisePropertyChanged("transaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transaccionSpecified {
            get {
                return this.transaccionFieldSpecified;
            }
            set {
                this.transaccionFieldSpecified = value;
                this.RaisePropertyChanged("transaccionSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class mensajeRecepcion : mensajeServicio {
        
        private bool advertenciaField;
        
        private bool advertenciaFieldSpecified;
        
        private int numeroArchivoField;
        
        private bool numeroArchivoFieldSpecified;
        
        private int numeroDetalleField;
        
        private bool numeroDetalleFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool advertencia {
            get {
                return this.advertenciaField;
            }
            set {
                this.advertenciaField = value;
                this.RaisePropertyChanged("advertencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool advertenciaSpecified {
            get {
                return this.advertenciaFieldSpecified;
            }
            set {
                this.advertenciaFieldSpecified = value;
                this.RaisePropertyChanged("advertenciaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int numeroArchivo {
            get {
                return this.numeroArchivoField;
            }
            set {
                this.numeroArchivoField = value;
                this.RaisePropertyChanged("numeroArchivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroArchivoSpecified {
            get {
                return this.numeroArchivoFieldSpecified;
            }
            set {
                this.numeroArchivoFieldSpecified = value;
                this.RaisePropertyChanged("numeroArchivoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int numeroDetalle {
            get {
                return this.numeroDetalleField;
            }
            set {
                this.numeroDetalleField = value;
                this.RaisePropertyChanged("numeroDetalle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroDetalleSpecified {
            get {
                return this.numeroDetalleFieldSpecified;
            }
            set {
                this.numeroDetalleFieldSpecified = value;
                this.RaisePropertyChanged("numeroDetalleSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaRecepcion : modelDto {
        
        private string codigoDescripcionField;
        
        private int codigoEstadoField;
        
        private bool codigoEstadoFieldSpecified;
        
        private string codigoRecepcionField;
        
        private mensajeRecepcion[] mensajesListField;
        
        private bool transaccionField;
        
        private bool transaccionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoDescripcion {
            get {
                return this.codigoDescripcionField;
            }
            set {
                this.codigoDescripcionField = value;
                this.RaisePropertyChanged("codigoDescripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoEstado {
            get {
                return this.codigoEstadoField;
            }
            set {
                this.codigoEstadoField = value;
                this.RaisePropertyChanged("codigoEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoEstadoSpecified {
            get {
                return this.codigoEstadoFieldSpecified;
            }
            set {
                this.codigoEstadoFieldSpecified = value;
                this.RaisePropertyChanged("codigoEstadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codigoRecepcion {
            get {
                return this.codigoRecepcionField;
            }
            set {
                this.codigoRecepcionField = value;
                this.RaisePropertyChanged("codigoRecepcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensajesList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public mensajeRecepcion[] mensajesList {
            get {
                return this.mensajesListField;
            }
            set {
                this.mensajesListField = value;
                this.RaisePropertyChanged("mensajesList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool transaccion {
            get {
                return this.transaccionField;
            }
            set {
                this.transaccionField = value;
                this.RaisePropertyChanged("transaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transaccionSpecified {
            get {
                return this.transaccionFieldSpecified;
            }
            set {
                this.transaccionFieldSpecified = value;
                this.RaisePropertyChanged("transaccionSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudConsultaCompras))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudAnulacionCompra))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionCompras))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudValidacionRecepcionCompras))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudCompras : modelDto {
        
        private int codigoAmbienteField;
        
        private int codigoPuntoVentaField;
        
        private string codigoSistemaField;
        
        private int codigoSucursalField;
        
        private string cufdField;
        
        private string cuisField;
        
        private long nitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoAmbiente {
            get {
                return this.codigoAmbienteField;
            }
            set {
                this.codigoAmbienteField = value;
                this.RaisePropertyChanged("codigoAmbiente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoPuntoVenta {
            get {
                return this.codigoPuntoVentaField;
            }
            set {
                this.codigoPuntoVentaField = value;
                this.RaisePropertyChanged("codigoPuntoVenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codigoSistema {
            get {
                return this.codigoSistemaField;
            }
            set {
                this.codigoSistemaField = value;
                this.RaisePropertyChanged("codigoSistema");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int codigoSucursal {
            get {
                return this.codigoSucursalField;
            }
            set {
                this.codigoSucursalField = value;
                this.RaisePropertyChanged("codigoSucursal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string cufd {
            get {
                return this.cufdField;
            }
            set {
                this.cufdField = value;
                this.RaisePropertyChanged("cufd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string cuis {
            get {
                return this.cuisField;
            }
            set {
                this.cuisField = value;
                this.RaisePropertyChanged("cuis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public long nit {
            get {
                return this.nitField;
            }
            set {
                this.nitField = value;
                this.RaisePropertyChanged("nit");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudConsultaCompras : solicitudCompras {
        
        private System.DateTime fechaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudAnulacionCompra : solicitudCompras {
        
        private string codAutorizacionField;
        
        private long nitProveedorField;
        
        private string nroDuiDimField;
        
        private long nroFacturaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codAutorizacion {
            get {
                return this.codAutorizacionField;
            }
            set {
                this.codAutorizacionField = value;
                this.RaisePropertyChanged("codAutorizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long nitProveedor {
            get {
                return this.nitProveedorField;
            }
            set {
                this.nitProveedorField = value;
                this.RaisePropertyChanged("nitProveedor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nroDuiDim {
            get {
                return this.nroDuiDimField;
            }
            set {
                this.nroDuiDimField = value;
                this.RaisePropertyChanged("nroDuiDim");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long nroFactura {
            get {
                return this.nroFacturaField;
            }
            set {
                this.nroFacturaField = value;
                this.RaisePropertyChanged("nroFactura");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudRecepcionCompras : solicitudCompras {
        
        private byte[] archivoField;
        
        private int cantidadFacturasField;
        
        private System.DateTime fechaEnvioField;
        
        private int gestionField;
        
        private string hashArchivoField;
        
        private int periodoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] archivo {
            get {
                return this.archivoField;
            }
            set {
                this.archivoField = value;
                this.RaisePropertyChanged("archivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int cantidadFacturas {
            get {
                return this.cantidadFacturasField;
            }
            set {
                this.cantidadFacturasField = value;
                this.RaisePropertyChanged("cantidadFacturas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaEnvio {
            get {
                return this.fechaEnvioField;
            }
            set {
                this.fechaEnvioField = value;
                this.RaisePropertyChanged("fechaEnvio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int gestion {
            get {
                return this.gestionField;
            }
            set {
                this.gestionField = value;
                this.RaisePropertyChanged("gestion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string hashArchivo {
            get {
                return this.hashArchivoField;
            }
            set {
                this.hashArchivoField = value;
                this.RaisePropertyChanged("hashArchivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
                this.RaisePropertyChanged("periodo");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudValidacionRecepcionCompras : solicitudCompras {
        
        private string codigoRecepcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoRecepcion {
            get {
                return this.codigoRecepcionField;
            }
            set {
                this.codigoRecepcionField = value;
                this.RaisePropertyChanged("codigoRecepcion");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarComunicacion", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class verificarComunicacion {
        
        public verificarComunicacion() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarComunicacionResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class verificarComunicacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PryCertificaSIN.ServiceRecepcionComprasSIN.respuestaComunicacion @return;
        
        public verificarComunicacionResponse() {
        }
        
        public verificarComunicacionResponse(PryCertificaSIN.ServiceRecepcionComprasSIN.respuestaComunicacion @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validacionRecepcionPaqueteCompras", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class validacionRecepcionPaqueteCompras {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PryCertificaSIN.ServiceRecepcionComprasSIN.solicitudValidacionRecepcionCompras SolicitudValidacionRecepcionCompras;
        
        public validacionRecepcionPaqueteCompras() {
        }
        
        public validacionRecepcionPaqueteCompras(PryCertificaSIN.ServiceRecepcionComprasSIN.solicitudValidacionRecepcionCompras SolicitudValidacionRecepcionCompras) {
            this.SolicitudValidacionRecepcionCompras = SolicitudValidacionRecepcionCompras;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validacionRecepcionPaqueteComprasResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class validacionRecepcionPaqueteComprasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PryCertificaSIN.ServiceRecepcionComprasSIN.respuestaRecepcion RespuestaServicioFacturacion;
        
        public validacionRecepcionPaqueteComprasResponse() {
        }
        
        public validacionRecepcionPaqueteComprasResponse(PryCertificaSIN.ServiceRecepcionComprasSIN.respuestaRecepcion RespuestaServicioFacturacion) {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionPaqueteCompras", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class recepcionPaqueteCompras {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PryCertificaSIN.ServiceRecepcionComprasSIN.solicitudRecepcionCompras SolicitudRecepcionCompras;
        
        public recepcionPaqueteCompras() {
        }
        
        public recepcionPaqueteCompras(PryCertificaSIN.ServiceRecepcionComprasSIN.solicitudRecepcionCompras SolicitudRecepcionCompras) {
            this.SolicitudRecepcionCompras = SolicitudRecepcionCompras;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionPaqueteComprasResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class recepcionPaqueteComprasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PryCertificaSIN.ServiceRecepcionComprasSIN.respuestaRecepcion RespuestaServicioFacturacion;
        
        public recepcionPaqueteComprasResponse() {
        }
        
        public recepcionPaqueteComprasResponse(PryCertificaSIN.ServiceRecepcionComprasSIN.respuestaRecepcion RespuestaServicioFacturacion) {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="anulacionCompra", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class anulacionCompra {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PryCertificaSIN.ServiceRecepcionComprasSIN.solicitudAnulacionCompra SolicitudAnulacionCompra;
        
        public anulacionCompra() {
        }
        
        public anulacionCompra(PryCertificaSIN.ServiceRecepcionComprasSIN.solicitudAnulacionCompra SolicitudAnulacionCompra) {
            this.SolicitudAnulacionCompra = SolicitudAnulacionCompra;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="anulacionCompraResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class anulacionCompraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PryCertificaSIN.ServiceRecepcionComprasSIN.respuestaRecepcion RespuestaServicioFacturacion;
        
        public anulacionCompraResponse() {
        }
        
        public anulacionCompraResponse(PryCertificaSIN.ServiceRecepcionComprasSIN.respuestaRecepcion RespuestaServicioFacturacion) {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="confirmacionCompras", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class confirmacionCompras {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PryCertificaSIN.ServiceRecepcionComprasSIN.solicitudRecepcionCompras SolicitudConfirmacionCompras;
        
        public confirmacionCompras() {
        }
        
        public confirmacionCompras(PryCertificaSIN.ServiceRecepcionComprasSIN.solicitudRecepcionCompras SolicitudConfirmacionCompras) {
            this.SolicitudConfirmacionCompras = SolicitudConfirmacionCompras;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="confirmacionComprasResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class confirmacionComprasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PryCertificaSIN.ServiceRecepcionComprasSIN.respuestaRecepcion RespuestaServicioFacturacion;
        
        public confirmacionComprasResponse() {
        }
        
        public confirmacionComprasResponse(PryCertificaSIN.ServiceRecepcionComprasSIN.respuestaRecepcion RespuestaServicioFacturacion) {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultaCompras", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class consultaCompras {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PryCertificaSIN.ServiceRecepcionComprasSIN.solicitudConsultaCompras SolicitudConsultaCompras;
        
        public consultaCompras() {
        }
        
        public consultaCompras(PryCertificaSIN.ServiceRecepcionComprasSIN.solicitudConsultaCompras SolicitudConsultaCompras) {
            this.SolicitudConsultaCompras = SolicitudConsultaCompras;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultaComprasResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class consultaComprasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PryCertificaSIN.ServiceRecepcionComprasSIN.respuestaConsultaCompras RespuestaServicioFacturacion;
        
        public consultaComprasResponse() {
        }
        
        public consultaComprasResponse(PryCertificaSIN.ServiceRecepcionComprasSIN.respuestaConsultaCompras RespuestaServicioFacturacion) {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioFacturacionChannel : PryCertificaSIN.ServiceRecepcionComprasSIN.ServicioFacturacion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioFacturacionClient : System.ServiceModel.ClientBase<PryCertificaSIN.ServiceRecepcionComprasSIN.ServicioFacturacion>, PryCertificaSIN.ServiceRecepcionComprasSIN.ServicioFacturacion {
        
        public ServicioFacturacionClient() {
        }
        
        public ServicioFacturacionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioFacturacionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioFacturacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioFacturacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PryCertificaSIN.ServiceRecepcionComprasSIN.verificarComunicacionResponse PryCertificaSIN.ServiceRecepcionComprasSIN.ServicioFacturacion.verificarComunicacion(PryCertificaSIN.ServiceRecepcionComprasSIN.verificarComunicacion request) {
            return base.Channel.verificarComunicacion(request);
        }
        
        public PryCertificaSIN.ServiceRecepcionComprasSIN.respuestaComunicacion verificarComunicacion() {
            PryCertificaSIN.ServiceRecepcionComprasSIN.verificarComunicacion inValue = new PryCertificaSIN.ServiceRecepcionComprasSIN.verificarComunicacion();
            PryCertificaSIN.ServiceRecepcionComprasSIN.verificarComunicacionResponse retVal = ((PryCertificaSIN.ServiceRecepcionComprasSIN.ServicioFacturacion)(this)).verificarComunicacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PryCertificaSIN.ServiceRecepcionComprasSIN.verificarComunicacionResponse> PryCertificaSIN.ServiceRecepcionComprasSIN.ServicioFacturacion.verificarComunicacionAsync(PryCertificaSIN.ServiceRecepcionComprasSIN.verificarComunicacion request) {
            return base.Channel.verificarComunicacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<PryCertificaSIN.ServiceRecepcionComprasSIN.verificarComunicacionResponse> verificarComunicacionAsync() {
            PryCertificaSIN.ServiceRecepcionComprasSIN.verificarComunicacion inValue = new PryCertificaSIN.ServiceRecepcionComprasSIN.verificarComunicacion();
            return ((PryCertificaSIN.ServiceRecepcionComprasSIN.ServicioFacturacion)(this)).verificarComunicacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PryCertificaSIN.ServiceRecepcionComprasSIN.validacionRecepcionPaqueteComprasResponse PryCertificaSIN.ServiceRecepcionComprasSIN.ServicioFacturacion.validacionRecepcionPaqueteCompras(PryCertificaSIN.ServiceRecepcionComprasSIN.validacionRecepcionPaqueteCompras request) {
            return base.Channel.validacionRecepcionPaqueteCompras(request);
        }
        
        public PryCertificaSIN.ServiceRecepcionComprasSIN.respuestaRecepcion validacionRecepcionPaqueteCompras(PryCertificaSIN.ServiceRecepcionComprasSIN.solicitudValidacionRecepcionCompras SolicitudValidacionRecepcionCompras) {
            PryCertificaSIN.ServiceRecepcionComprasSIN.validacionRecepcionPaqueteCompras inValue = new PryCertificaSIN.ServiceRecepcionComprasSIN.validacionRecepcionPaqueteCompras();
            inValue.SolicitudValidacionRecepcionCompras = SolicitudValidacionRecepcionCompras;
            PryCertificaSIN.ServiceRecepcionComprasSIN.validacionRecepcionPaqueteComprasResponse retVal = ((PryCertificaSIN.ServiceRecepcionComprasSIN.ServicioFacturacion)(this)).validacionRecepcionPaqueteCompras(inValue);
            return retVal.RespuestaServicioFacturacion;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PryCertificaSIN.ServiceRecepcionComprasSIN.validacionRecepcionPaqueteComprasResponse> PryCertificaSIN.ServiceRecepcionComprasSIN.ServicioFacturacion.validacionRecepcionPaqueteComprasAsync(PryCertificaSIN.ServiceRecepcionComprasSIN.validacionRecepcionPaqueteCompras request) {
            return base.Channel.validacionRecepcionPaqueteComprasAsync(request);
        }
        
        public System.Threading.Tasks.Task<PryCertificaSIN.ServiceRecepcionComprasSIN.validacionRecepcionPaqueteComprasResponse> validacionRecepcionPaqueteComprasAsync(PryCertificaSIN.ServiceRecepcionComprasSIN.solicitudValidacionRecepcionCompras SolicitudValidacionRecepcionCompras) {
            PryCertificaSIN.ServiceRecepcionComprasSIN.validacionRecepcionPaqueteCompras inValue = new PryCertificaSIN.ServiceRecepcionComprasSIN.validacionRecepcionPaqueteCompras();
            inValue.SolicitudValidacionRecepcionCompras = SolicitudValidacionRecepcionCompras;
            return ((PryCertificaSIN.ServiceRecepcionComprasSIN.ServicioFacturacion)(this)).validacionRecepcionPaqueteComprasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PryCertificaSIN.ServiceRecepcionComprasSIN.recepcionPaqueteComprasResponse PryCertificaSIN.ServiceRecepcionComprasSIN.ServicioFacturacion.recepcionPaqueteCompras(PryCertificaSIN.ServiceRecepcionComprasSIN.recepcionPaqueteCompras request) {
            return base.Channel.recepcionPaqueteCompras(request);
        }
        
        public PryCertificaSIN.ServiceRecepcionComprasSIN.respuestaRecepcion recepcionPaqueteCompras(PryCertificaSIN.ServiceRecepcionComprasSIN.solicitudRecepcionCompras SolicitudRecepcionCompras) {
            PryCertificaSIN.ServiceRecepcionComprasSIN.recepcionPaqueteCompras inValue = new PryCertificaSIN.ServiceRecepcionComprasSIN.recepcionPaqueteCompras();
            inValue.SolicitudRecepcionCompras = SolicitudRecepcionCompras;
            PryCertificaSIN.ServiceRecepcionComprasSIN.recepcionPaqueteComprasResponse retVal = ((PryCertificaSIN.ServiceRecepcionComprasSIN.ServicioFacturacion)(this)).recepcionPaqueteCompras(inValue);
            return retVal.RespuestaServicioFacturacion;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PryCertificaSIN.ServiceRecepcionComprasSIN.recepcionPaqueteComprasResponse> PryCertificaSIN.ServiceRecepcionComprasSIN.ServicioFacturacion.recepcionPaqueteComprasAsync(PryCertificaSIN.ServiceRecepcionComprasSIN.recepcionPaqueteCompras request) {
            return base.Channel.recepcionPaqueteComprasAsync(request);
        }
        
        public System.Threading.Tasks.Task<PryCertificaSIN.ServiceRecepcionComprasSIN.recepcionPaqueteComprasResponse> recepcionPaqueteComprasAsync(PryCertificaSIN.ServiceRecepcionComprasSIN.solicitudRecepcionCompras SolicitudRecepcionCompras) {
            PryCertificaSIN.ServiceRecepcionComprasSIN.recepcionPaqueteCompras inValue = new PryCertificaSIN.ServiceRecepcionComprasSIN.recepcionPaqueteCompras();
            inValue.SolicitudRecepcionCompras = SolicitudRecepcionCompras;
            return ((PryCertificaSIN.ServiceRecepcionComprasSIN.ServicioFacturacion)(this)).recepcionPaqueteComprasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PryCertificaSIN.ServiceRecepcionComprasSIN.anulacionCompraResponse PryCertificaSIN.ServiceRecepcionComprasSIN.ServicioFacturacion.anulacionCompra(PryCertificaSIN.ServiceRecepcionComprasSIN.anulacionCompra request) {
            return base.Channel.anulacionCompra(request);
        }
        
        public PryCertificaSIN.ServiceRecepcionComprasSIN.respuestaRecepcion anulacionCompra(PryCertificaSIN.ServiceRecepcionComprasSIN.solicitudAnulacionCompra SolicitudAnulacionCompra) {
            PryCertificaSIN.ServiceRecepcionComprasSIN.anulacionCompra inValue = new PryCertificaSIN.ServiceRecepcionComprasSIN.anulacionCompra();
            inValue.SolicitudAnulacionCompra = SolicitudAnulacionCompra;
            PryCertificaSIN.ServiceRecepcionComprasSIN.anulacionCompraResponse retVal = ((PryCertificaSIN.ServiceRecepcionComprasSIN.ServicioFacturacion)(this)).anulacionCompra(inValue);
            return retVal.RespuestaServicioFacturacion;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PryCertificaSIN.ServiceRecepcionComprasSIN.anulacionCompraResponse> PryCertificaSIN.ServiceRecepcionComprasSIN.ServicioFacturacion.anulacionCompraAsync(PryCertificaSIN.ServiceRecepcionComprasSIN.anulacionCompra request) {
            return base.Channel.anulacionCompraAsync(request);
        }
        
        public System.Threading.Tasks.Task<PryCertificaSIN.ServiceRecepcionComprasSIN.anulacionCompraResponse> anulacionCompraAsync(PryCertificaSIN.ServiceRecepcionComprasSIN.solicitudAnulacionCompra SolicitudAnulacionCompra) {
            PryCertificaSIN.ServiceRecepcionComprasSIN.anulacionCompra inValue = new PryCertificaSIN.ServiceRecepcionComprasSIN.anulacionCompra();
            inValue.SolicitudAnulacionCompra = SolicitudAnulacionCompra;
            return ((PryCertificaSIN.ServiceRecepcionComprasSIN.ServicioFacturacion)(this)).anulacionCompraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PryCertificaSIN.ServiceRecepcionComprasSIN.confirmacionComprasResponse PryCertificaSIN.ServiceRecepcionComprasSIN.ServicioFacturacion.confirmacionCompras(PryCertificaSIN.ServiceRecepcionComprasSIN.confirmacionCompras request) {
            return base.Channel.confirmacionCompras(request);
        }
        
        public PryCertificaSIN.ServiceRecepcionComprasSIN.respuestaRecepcion confirmacionCompras(PryCertificaSIN.ServiceRecepcionComprasSIN.solicitudRecepcionCompras SolicitudConfirmacionCompras) {
            PryCertificaSIN.ServiceRecepcionComprasSIN.confirmacionCompras inValue = new PryCertificaSIN.ServiceRecepcionComprasSIN.confirmacionCompras();
            inValue.SolicitudConfirmacionCompras = SolicitudConfirmacionCompras;
            PryCertificaSIN.ServiceRecepcionComprasSIN.confirmacionComprasResponse retVal = ((PryCertificaSIN.ServiceRecepcionComprasSIN.ServicioFacturacion)(this)).confirmacionCompras(inValue);
            return retVal.RespuestaServicioFacturacion;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PryCertificaSIN.ServiceRecepcionComprasSIN.confirmacionComprasResponse> PryCertificaSIN.ServiceRecepcionComprasSIN.ServicioFacturacion.confirmacionComprasAsync(PryCertificaSIN.ServiceRecepcionComprasSIN.confirmacionCompras request) {
            return base.Channel.confirmacionComprasAsync(request);
        }
        
        public System.Threading.Tasks.Task<PryCertificaSIN.ServiceRecepcionComprasSIN.confirmacionComprasResponse> confirmacionComprasAsync(PryCertificaSIN.ServiceRecepcionComprasSIN.solicitudRecepcionCompras SolicitudConfirmacionCompras) {
            PryCertificaSIN.ServiceRecepcionComprasSIN.confirmacionCompras inValue = new PryCertificaSIN.ServiceRecepcionComprasSIN.confirmacionCompras();
            inValue.SolicitudConfirmacionCompras = SolicitudConfirmacionCompras;
            return ((PryCertificaSIN.ServiceRecepcionComprasSIN.ServicioFacturacion)(this)).confirmacionComprasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PryCertificaSIN.ServiceRecepcionComprasSIN.consultaComprasResponse PryCertificaSIN.ServiceRecepcionComprasSIN.ServicioFacturacion.consultaCompras(PryCertificaSIN.ServiceRecepcionComprasSIN.consultaCompras request) {
            return base.Channel.consultaCompras(request);
        }
        
        public PryCertificaSIN.ServiceRecepcionComprasSIN.respuestaConsultaCompras consultaCompras(PryCertificaSIN.ServiceRecepcionComprasSIN.solicitudConsultaCompras SolicitudConsultaCompras) {
            PryCertificaSIN.ServiceRecepcionComprasSIN.consultaCompras inValue = new PryCertificaSIN.ServiceRecepcionComprasSIN.consultaCompras();
            inValue.SolicitudConsultaCompras = SolicitudConsultaCompras;
            PryCertificaSIN.ServiceRecepcionComprasSIN.consultaComprasResponse retVal = ((PryCertificaSIN.ServiceRecepcionComprasSIN.ServicioFacturacion)(this)).consultaCompras(inValue);
            return retVal.RespuestaServicioFacturacion;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PryCertificaSIN.ServiceRecepcionComprasSIN.consultaComprasResponse> PryCertificaSIN.ServiceRecepcionComprasSIN.ServicioFacturacion.consultaComprasAsync(PryCertificaSIN.ServiceRecepcionComprasSIN.consultaCompras request) {
            return base.Channel.consultaComprasAsync(request);
        }
        
        public System.Threading.Tasks.Task<PryCertificaSIN.ServiceRecepcionComprasSIN.consultaComprasResponse> consultaComprasAsync(PryCertificaSIN.ServiceRecepcionComprasSIN.solicitudConsultaCompras SolicitudConsultaCompras) {
            PryCertificaSIN.ServiceRecepcionComprasSIN.consultaCompras inValue = new PryCertificaSIN.ServiceRecepcionComprasSIN.consultaCompras();
            inValue.SolicitudConsultaCompras = SolicitudConsultaCompras;
            return ((PryCertificaSIN.ServiceRecepcionComprasSIN.ServicioFacturacion)(this)).consultaComprasAsync(inValue);
        }
    }
}
