//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PryCertificaSIN.ServiceFacturacionCompraVentaSIN {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://siat.impuestos.gob.bo/", ConfigurationName="ServiceFacturacionCompraVentaSIN.ServicioFacturacion")]
    public interface ServicioFacturacion {
        
        // CODEGEN: El parámetro 'RespuestaServicioFacturacion' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaServicioFacturacion")]
        PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionPaqueteFacturaResponse recepcionPaqueteFactura(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionPaqueteFactura request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionPaqueteFacturaResponse> recepcionPaqueteFacturaAsync(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionPaqueteFactura request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PryCertificaSIN.ServiceFacturacionCompraVentaSIN.verificarComunicacionResponse verificarComunicacion(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.verificarComunicacion request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PryCertificaSIN.ServiceFacturacionCompraVentaSIN.verificarComunicacionResponse> verificarComunicacionAsync(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.verificarComunicacion request);
        
        // CODEGEN: El parámetro 'RespuestaServicioFacturacion' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaServicioFacturacion")]
        PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionFacturaResponse recepcionFactura(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionFactura request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionFacturaResponse> recepcionFacturaAsync(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionFactura request);
        
        // CODEGEN: El parámetro 'RespuestaServicioFacturacion' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaServicioFacturacion")]
        PryCertificaSIN.ServiceFacturacionCompraVentaSIN.validacionRecepcionMasivaFacturaResponse validacionRecepcionMasivaFactura(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.validacionRecepcionMasivaFactura request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PryCertificaSIN.ServiceFacturacionCompraVentaSIN.validacionRecepcionMasivaFacturaResponse> validacionRecepcionMasivaFacturaAsync(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.validacionRecepcionMasivaFactura request);
        
        // CODEGEN: El parámetro 'RespuestaRecepcionAnexos' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaRecepcionAnexos")]
        PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionAnexosResponse recepcionAnexos(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionAnexos request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionAnexosResponse> recepcionAnexosAsync(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionAnexos request);
        
        // CODEGEN: El parámetro 'RespuestaServicioFacturacion' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaServicioFacturacion")]
        PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionMasivaFacturaResponse recepcionMasivaFactura(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionMasivaFactura request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionMasivaFacturaResponse> recepcionMasivaFacturaAsync(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionMasivaFactura request);
        
        // CODEGEN: El parámetro 'RespuestaServicioFacturacion' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaServicioFacturacion")]
        PryCertificaSIN.ServiceFacturacionCompraVentaSIN.verificacionEstadoFacturaResponse verificacionEstadoFactura(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.verificacionEstadoFactura request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PryCertificaSIN.ServiceFacturacionCompraVentaSIN.verificacionEstadoFacturaResponse> verificacionEstadoFacturaAsync(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.verificacionEstadoFactura request);
        
        // CODEGEN: El parámetro 'RespuestaServicioFacturacion' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaServicioFacturacion")]
        PryCertificaSIN.ServiceFacturacionCompraVentaSIN.validacionRecepcionPaqueteFacturaResponse validacionRecepcionPaqueteFactura(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.validacionRecepcionPaqueteFactura request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PryCertificaSIN.ServiceFacturacionCompraVentaSIN.validacionRecepcionPaqueteFacturaResponse> validacionRecepcionPaqueteFacturaAsync(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.validacionRecepcionPaqueteFactura request);
        
        // CODEGEN: El parámetro 'RespuestaServicioFacturacion' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaServicioFacturacion")]
        PryCertificaSIN.ServiceFacturacionCompraVentaSIN.anulacionFacturaResponse anulacionFactura(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.anulacionFactura request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PryCertificaSIN.ServiceFacturacionCompraVentaSIN.anulacionFacturaResponse> anulacionFacturaAsync(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.anulacionFactura request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudRecepcionPaquete : solicitudRecepcionFactura {
        
        private string cafcField;
        
        private int cantidadFacturasField;
        
        private long codigoEventoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cafc {
            get {
                return this.cafcField;
            }
            set {
                this.cafcField = value;
                this.RaisePropertyChanged("cafc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int cantidadFacturas {
            get {
                return this.cantidadFacturasField;
            }
            set {
                this.cantidadFacturasField = value;
                this.RaisePropertyChanged("cantidadFacturas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long codigoEvento {
            get {
                return this.codigoEventoField;
            }
            set {
                this.codigoEventoField = value;
                this.RaisePropertyChanged("codigoEvento");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionMasiva))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionPaquete))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudRecepcionFactura : solicitudRecepcion {
        
        private byte[] archivoField;
        
        private string fechaEnvioField;
        
        private string hashArchivoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] archivo {
            get {
                return this.archivoField;
            }
            set {
                this.archivoField = value;
                this.RaisePropertyChanged("archivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fechaEnvio {
            get {
                return this.fechaEnvioField;
            }
            set {
                this.fechaEnvioField = value;
                this.RaisePropertyChanged("fechaEnvio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string hashArchivo {
            get {
                return this.hashArchivoField;
            }
            set {
                this.hashArchivoField = value;
                this.RaisePropertyChanged("hashArchivo");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudAnulacion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudVerificacionEstado))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionAnexos))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudValidacionRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionFactura))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionMasiva))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionPaquete))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudRecepcion : modelDto {
        
        private int codigoAmbienteField;
        
        private int codigoDocumentoSectorField;
        
        private int codigoEmisionField;
        
        private int codigoModalidadField;
        
        private int codigoPuntoVentaField;
        
        private bool codigoPuntoVentaFieldSpecified;
        
        private string codigoSistemaField;
        
        private int codigoSucursalField;
        
        private string cufdField;
        
        private string cuisField;
        
        private long nitField;
        
        private int tipoFacturaDocumentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoAmbiente {
            get {
                return this.codigoAmbienteField;
            }
            set {
                this.codigoAmbienteField = value;
                this.RaisePropertyChanged("codigoAmbiente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoDocumentoSector {
            get {
                return this.codigoDocumentoSectorField;
            }
            set {
                this.codigoDocumentoSectorField = value;
                this.RaisePropertyChanged("codigoDocumentoSector");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int codigoEmision {
            get {
                return this.codigoEmisionField;
            }
            set {
                this.codigoEmisionField = value;
                this.RaisePropertyChanged("codigoEmision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int codigoModalidad {
            get {
                return this.codigoModalidadField;
            }
            set {
                this.codigoModalidadField = value;
                this.RaisePropertyChanged("codigoModalidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int codigoPuntoVenta {
            get {
                return this.codigoPuntoVentaField;
            }
            set {
                this.codigoPuntoVentaField = value;
                this.RaisePropertyChanged("codigoPuntoVenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoPuntoVentaSpecified {
            get {
                return this.codigoPuntoVentaFieldSpecified;
            }
            set {
                this.codigoPuntoVentaFieldSpecified = value;
                this.RaisePropertyChanged("codigoPuntoVentaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string codigoSistema {
            get {
                return this.codigoSistemaField;
            }
            set {
                this.codigoSistemaField = value;
                this.RaisePropertyChanged("codigoSistema");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int codigoSucursal {
            get {
                return this.codigoSucursalField;
            }
            set {
                this.codigoSucursalField = value;
                this.RaisePropertyChanged("codigoSucursal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string cufd {
            get {
                return this.cufdField;
            }
            set {
                this.cufdField = value;
                this.RaisePropertyChanged("cufd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string cuis {
            get {
                return this.cuisField;
            }
            set {
                this.cuisField = value;
                this.RaisePropertyChanged("cuis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public long nit {
            get {
                return this.nitField;
            }
            set {
                this.nitField = value;
                this.RaisePropertyChanged("nit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int tipoFacturaDocumento {
            get {
                return this.tipoFacturaDocumentoField;
            }
            set {
                this.tipoFacturaDocumentoField = value;
                this.RaisePropertyChanged("tipoFacturaDocumento");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaComunicacion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mensajeServicio))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mensajeRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ventaAnexo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudAnulacion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudVerificacionEstado))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionAnexos))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudValidacionRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionFactura))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionMasiva))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionPaquete))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public abstract partial class modelDto : model {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(modelDto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaComunicacion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mensajeServicio))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mensajeRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ventaAnexo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudAnulacion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudVerificacionEstado))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionAnexos))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudValidacionRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionFactura))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionMasiva))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionPaquete))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public abstract partial class model : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaComunicacion : modelDto {
        
        private mensajeServicio[] mensajesListField;
        
        private bool transaccionField;
        
        private bool transaccionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensajesList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public mensajeServicio[] mensajesList {
            get {
                return this.mensajesListField;
            }
            set {
                this.mensajesListField = value;
                this.RaisePropertyChanged("mensajesList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool transaccion {
            get {
                return this.transaccionField;
            }
            set {
                this.transaccionField = value;
                this.RaisePropertyChanged("transaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transaccionSpecified {
            get {
                return this.transaccionFieldSpecified;
            }
            set {
                this.transaccionFieldSpecified = value;
                this.RaisePropertyChanged("transaccionSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mensajeRecepcion))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class mensajeServicio : modelDto {
        
        private int codigoField;
        
        private bool codigoFieldSpecified;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoSpecified {
            get {
                return this.codigoFieldSpecified;
            }
            set {
                this.codigoFieldSpecified = value;
                this.RaisePropertyChanged("codigoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class mensajeRecepcion : mensajeServicio {
        
        private bool advertenciaField;
        
        private bool advertenciaFieldSpecified;
        
        private int numeroArchivoField;
        
        private bool numeroArchivoFieldSpecified;
        
        private int numeroDetalleField;
        
        private bool numeroDetalleFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool advertencia {
            get {
                return this.advertenciaField;
            }
            set {
                this.advertenciaField = value;
                this.RaisePropertyChanged("advertencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool advertenciaSpecified {
            get {
                return this.advertenciaFieldSpecified;
            }
            set {
                this.advertenciaFieldSpecified = value;
                this.RaisePropertyChanged("advertenciaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int numeroArchivo {
            get {
                return this.numeroArchivoField;
            }
            set {
                this.numeroArchivoField = value;
                this.RaisePropertyChanged("numeroArchivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroArchivoSpecified {
            get {
                return this.numeroArchivoFieldSpecified;
            }
            set {
                this.numeroArchivoFieldSpecified = value;
                this.RaisePropertyChanged("numeroArchivoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int numeroDetalle {
            get {
                return this.numeroDetalleField;
            }
            set {
                this.numeroDetalleField = value;
                this.RaisePropertyChanged("numeroDetalle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroDetalleSpecified {
            get {
                return this.numeroDetalleFieldSpecified;
            }
            set {
                this.numeroDetalleFieldSpecified = value;
                this.RaisePropertyChanged("numeroDetalleSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaRecepcion : modelDto {
        
        private string codigoDescripcionField;
        
        private int codigoEstadoField;
        
        private bool codigoEstadoFieldSpecified;
        
        private string codigoRecepcionField;
        
        private mensajeRecepcion[] mensajesListField;
        
        private bool transaccionField;
        
        private bool transaccionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoDescripcion {
            get {
                return this.codigoDescripcionField;
            }
            set {
                this.codigoDescripcionField = value;
                this.RaisePropertyChanged("codigoDescripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoEstado {
            get {
                return this.codigoEstadoField;
            }
            set {
                this.codigoEstadoField = value;
                this.RaisePropertyChanged("codigoEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoEstadoSpecified {
            get {
                return this.codigoEstadoFieldSpecified;
            }
            set {
                this.codigoEstadoFieldSpecified = value;
                this.RaisePropertyChanged("codigoEstadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codigoRecepcion {
            get {
                return this.codigoRecepcionField;
            }
            set {
                this.codigoRecepcionField = value;
                this.RaisePropertyChanged("codigoRecepcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensajesList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public mensajeRecepcion[] mensajesList {
            get {
                return this.mensajesListField;
            }
            set {
                this.mensajesListField = value;
                this.RaisePropertyChanged("mensajesList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool transaccion {
            get {
                return this.transaccionField;
            }
            set {
                this.transaccionField = value;
                this.RaisePropertyChanged("transaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transaccionSpecified {
            get {
                return this.transaccionFieldSpecified;
            }
            set {
                this.transaccionFieldSpecified = value;
                this.RaisePropertyChanged("transaccionSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class ventaAnexo : modelDto {
        
        private string codigoField;
        
        private string codigoProductoField;
        
        private long codigoProductoSinField;
        
        private string tipoCodigoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigoProducto {
            get {
                return this.codigoProductoField;
            }
            set {
                this.codigoProductoField = value;
                this.RaisePropertyChanged("codigoProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long codigoProductoSin {
            get {
                return this.codigoProductoSinField;
            }
            set {
                this.codigoProductoSinField = value;
                this.RaisePropertyChanged("codigoProductoSin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string tipoCodigo {
            get {
                return this.tipoCodigoField;
            }
            set {
                this.tipoCodigoField = value;
                this.RaisePropertyChanged("tipoCodigo");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudAnulacion : solicitudRecepcion {
        
        private int codigoMotivoField;
        
        private string cufField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoMotivo {
            get {
                return this.codigoMotivoField;
            }
            set {
                this.codigoMotivoField = value;
                this.RaisePropertyChanged("codigoMotivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string cuf {
            get {
                return this.cufField;
            }
            set {
                this.cufField = value;
                this.RaisePropertyChanged("cuf");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudVerificacionEstado : solicitudRecepcion {
        
        private string cufField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cuf {
            get {
                return this.cufField;
            }
            set {
                this.cufField = value;
                this.RaisePropertyChanged("cuf");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudRecepcionAnexos : solicitudRecepcion {
        
        private ventaAnexo[] anexosListField;
        
        private string cufField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("anexosList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ventaAnexo[] anexosList {
            get {
                return this.anexosListField;
            }
            set {
                this.anexosListField = value;
                this.RaisePropertyChanged("anexosList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string cuf {
            get {
                return this.cufField;
            }
            set {
                this.cufField = value;
                this.RaisePropertyChanged("cuf");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudValidacionRecepcion : solicitudRecepcion {
        
        private string codigoRecepcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoRecepcion {
            get {
                return this.codigoRecepcionField;
            }
            set {
                this.codigoRecepcionField = value;
                this.RaisePropertyChanged("codigoRecepcion");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudRecepcionMasiva : solicitudRecepcionFactura {
        
        private int cantidadFacturasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantidadFacturas {
            get {
                return this.cantidadFacturasField;
            }
            set {
                this.cantidadFacturasField = value;
                this.RaisePropertyChanged("cantidadFacturas");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionPaqueteFactura", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class recepcionPaqueteFactura {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PryCertificaSIN.ServiceFacturacionCompraVentaSIN.solicitudRecepcionPaquete SolicitudServicioRecepcionPaquete;
        
        public recepcionPaqueteFactura() {
        }
        
        public recepcionPaqueteFactura(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.solicitudRecepcionPaquete SolicitudServicioRecepcionPaquete) {
            this.SolicitudServicioRecepcionPaquete = SolicitudServicioRecepcionPaquete;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionPaqueteFacturaResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class recepcionPaqueteFacturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PryCertificaSIN.ServiceFacturacionCompraVentaSIN.respuestaRecepcion RespuestaServicioFacturacion;
        
        public recepcionPaqueteFacturaResponse() {
        }
        
        public recepcionPaqueteFacturaResponse(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.respuestaRecepcion RespuestaServicioFacturacion) {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarComunicacion", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class verificarComunicacion {
        
        public verificarComunicacion() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarComunicacionResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class verificarComunicacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PryCertificaSIN.ServiceFacturacionCompraVentaSIN.respuestaComunicacion @return;
        
        public verificarComunicacionResponse() {
        }
        
        public verificarComunicacionResponse(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.respuestaComunicacion @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionFactura", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class recepcionFactura {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PryCertificaSIN.ServiceFacturacionCompraVentaSIN.solicitudRecepcionFactura SolicitudServicioRecepcionFactura;
        
        public recepcionFactura() {
        }
        
        public recepcionFactura(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.solicitudRecepcionFactura SolicitudServicioRecepcionFactura) {
            this.SolicitudServicioRecepcionFactura = SolicitudServicioRecepcionFactura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionFacturaResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class recepcionFacturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PryCertificaSIN.ServiceFacturacionCompraVentaSIN.respuestaRecepcion RespuestaServicioFacturacion;
        
        public recepcionFacturaResponse() {
        }
        
        public recepcionFacturaResponse(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.respuestaRecepcion RespuestaServicioFacturacion) {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validacionRecepcionMasivaFactura", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class validacionRecepcionMasivaFactura {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PryCertificaSIN.ServiceFacturacionCompraVentaSIN.solicitudValidacionRecepcion SolicitudServicioValidacionRecepcionMasiva;
        
        public validacionRecepcionMasivaFactura() {
        }
        
        public validacionRecepcionMasivaFactura(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.solicitudValidacionRecepcion SolicitudServicioValidacionRecepcionMasiva) {
            this.SolicitudServicioValidacionRecepcionMasiva = SolicitudServicioValidacionRecepcionMasiva;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validacionRecepcionMasivaFacturaResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class validacionRecepcionMasivaFacturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PryCertificaSIN.ServiceFacturacionCompraVentaSIN.respuestaRecepcion RespuestaServicioFacturacion;
        
        public validacionRecepcionMasivaFacturaResponse() {
        }
        
        public validacionRecepcionMasivaFacturaResponse(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.respuestaRecepcion RespuestaServicioFacturacion) {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionAnexos", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class recepcionAnexos {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PryCertificaSIN.ServiceFacturacionCompraVentaSIN.solicitudRecepcionAnexos SolicitudRecepcionAnexos;
        
        public recepcionAnexos() {
        }
        
        public recepcionAnexos(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.solicitudRecepcionAnexos SolicitudRecepcionAnexos) {
            this.SolicitudRecepcionAnexos = SolicitudRecepcionAnexos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionAnexosResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class recepcionAnexosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PryCertificaSIN.ServiceFacturacionCompraVentaSIN.respuestaRecepcion RespuestaRecepcionAnexos;
        
        public recepcionAnexosResponse() {
        }
        
        public recepcionAnexosResponse(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.respuestaRecepcion RespuestaRecepcionAnexos) {
            this.RespuestaRecepcionAnexos = RespuestaRecepcionAnexos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionMasivaFactura", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class recepcionMasivaFactura {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PryCertificaSIN.ServiceFacturacionCompraVentaSIN.solicitudRecepcionMasiva SolicitudServicioRecepcionMasiva;
        
        public recepcionMasivaFactura() {
        }
        
        public recepcionMasivaFactura(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.solicitudRecepcionMasiva SolicitudServicioRecepcionMasiva) {
            this.SolicitudServicioRecepcionMasiva = SolicitudServicioRecepcionMasiva;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionMasivaFacturaResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class recepcionMasivaFacturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PryCertificaSIN.ServiceFacturacionCompraVentaSIN.respuestaRecepcion RespuestaServicioFacturacion;
        
        public recepcionMasivaFacturaResponse() {
        }
        
        public recepcionMasivaFacturaResponse(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.respuestaRecepcion RespuestaServicioFacturacion) {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificacionEstadoFactura", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class verificacionEstadoFactura {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PryCertificaSIN.ServiceFacturacionCompraVentaSIN.solicitudVerificacionEstado SolicitudServicioVerificacionEstadoFactura;
        
        public verificacionEstadoFactura() {
        }
        
        public verificacionEstadoFactura(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.solicitudVerificacionEstado SolicitudServicioVerificacionEstadoFactura) {
            this.SolicitudServicioVerificacionEstadoFactura = SolicitudServicioVerificacionEstadoFactura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificacionEstadoFacturaResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class verificacionEstadoFacturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PryCertificaSIN.ServiceFacturacionCompraVentaSIN.respuestaRecepcion RespuestaServicioFacturacion;
        
        public verificacionEstadoFacturaResponse() {
        }
        
        public verificacionEstadoFacturaResponse(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.respuestaRecepcion RespuestaServicioFacturacion) {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validacionRecepcionPaqueteFactura", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class validacionRecepcionPaqueteFactura {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PryCertificaSIN.ServiceFacturacionCompraVentaSIN.solicitudValidacionRecepcion SolicitudServicioValidacionRecepcionPaquete;
        
        public validacionRecepcionPaqueteFactura() {
        }
        
        public validacionRecepcionPaqueteFactura(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.solicitudValidacionRecepcion SolicitudServicioValidacionRecepcionPaquete) {
            this.SolicitudServicioValidacionRecepcionPaquete = SolicitudServicioValidacionRecepcionPaquete;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validacionRecepcionPaqueteFacturaResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class validacionRecepcionPaqueteFacturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PryCertificaSIN.ServiceFacturacionCompraVentaSIN.respuestaRecepcion RespuestaServicioFacturacion;
        
        public validacionRecepcionPaqueteFacturaResponse() {
        }
        
        public validacionRecepcionPaqueteFacturaResponse(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.respuestaRecepcion RespuestaServicioFacturacion) {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="anulacionFactura", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class anulacionFactura {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PryCertificaSIN.ServiceFacturacionCompraVentaSIN.solicitudAnulacion SolicitudServicioAnulacionFactura;
        
        public anulacionFactura() {
        }
        
        public anulacionFactura(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.solicitudAnulacion SolicitudServicioAnulacionFactura) {
            this.SolicitudServicioAnulacionFactura = SolicitudServicioAnulacionFactura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="anulacionFacturaResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class anulacionFacturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PryCertificaSIN.ServiceFacturacionCompraVentaSIN.respuestaRecepcion RespuestaServicioFacturacion;
        
        public anulacionFacturaResponse() {
        }
        
        public anulacionFacturaResponse(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.respuestaRecepcion RespuestaServicioFacturacion) {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioFacturacionChannel : PryCertificaSIN.ServiceFacturacionCompraVentaSIN.ServicioFacturacion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioFacturacionClient : System.ServiceModel.ClientBase<PryCertificaSIN.ServiceFacturacionCompraVentaSIN.ServicioFacturacion>, PryCertificaSIN.ServiceFacturacionCompraVentaSIN.ServicioFacturacion {
        
        public ServicioFacturacionClient() {
        }
        
        public ServicioFacturacionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioFacturacionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioFacturacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioFacturacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionPaqueteFacturaResponse PryCertificaSIN.ServiceFacturacionCompraVentaSIN.ServicioFacturacion.recepcionPaqueteFactura(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionPaqueteFactura request) {
            return base.Channel.recepcionPaqueteFactura(request);
        }
        
        public PryCertificaSIN.ServiceFacturacionCompraVentaSIN.respuestaRecepcion recepcionPaqueteFactura(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.solicitudRecepcionPaquete SolicitudServicioRecepcionPaquete) {
            PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionPaqueteFactura inValue = new PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionPaqueteFactura();
            inValue.SolicitudServicioRecepcionPaquete = SolicitudServicioRecepcionPaquete;
            PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionPaqueteFacturaResponse retVal = ((PryCertificaSIN.ServiceFacturacionCompraVentaSIN.ServicioFacturacion)(this)).recepcionPaqueteFactura(inValue);
            return retVal.RespuestaServicioFacturacion;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionPaqueteFacturaResponse> PryCertificaSIN.ServiceFacturacionCompraVentaSIN.ServicioFacturacion.recepcionPaqueteFacturaAsync(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionPaqueteFactura request) {
            return base.Channel.recepcionPaqueteFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionPaqueteFacturaResponse> recepcionPaqueteFacturaAsync(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.solicitudRecepcionPaquete SolicitudServicioRecepcionPaquete) {
            PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionPaqueteFactura inValue = new PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionPaqueteFactura();
            inValue.SolicitudServicioRecepcionPaquete = SolicitudServicioRecepcionPaquete;
            return ((PryCertificaSIN.ServiceFacturacionCompraVentaSIN.ServicioFacturacion)(this)).recepcionPaqueteFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PryCertificaSIN.ServiceFacturacionCompraVentaSIN.verificarComunicacionResponse PryCertificaSIN.ServiceFacturacionCompraVentaSIN.ServicioFacturacion.verificarComunicacion(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.verificarComunicacion request) {
            return base.Channel.verificarComunicacion(request);
        }
        
        public PryCertificaSIN.ServiceFacturacionCompraVentaSIN.respuestaComunicacion verificarComunicacion() {
            PryCertificaSIN.ServiceFacturacionCompraVentaSIN.verificarComunicacion inValue = new PryCertificaSIN.ServiceFacturacionCompraVentaSIN.verificarComunicacion();
            PryCertificaSIN.ServiceFacturacionCompraVentaSIN.verificarComunicacionResponse retVal = ((PryCertificaSIN.ServiceFacturacionCompraVentaSIN.ServicioFacturacion)(this)).verificarComunicacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PryCertificaSIN.ServiceFacturacionCompraVentaSIN.verificarComunicacionResponse> PryCertificaSIN.ServiceFacturacionCompraVentaSIN.ServicioFacturacion.verificarComunicacionAsync(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.verificarComunicacion request) {
            return base.Channel.verificarComunicacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<PryCertificaSIN.ServiceFacturacionCompraVentaSIN.verificarComunicacionResponse> verificarComunicacionAsync() {
            PryCertificaSIN.ServiceFacturacionCompraVentaSIN.verificarComunicacion inValue = new PryCertificaSIN.ServiceFacturacionCompraVentaSIN.verificarComunicacion();
            return ((PryCertificaSIN.ServiceFacturacionCompraVentaSIN.ServicioFacturacion)(this)).verificarComunicacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionFacturaResponse PryCertificaSIN.ServiceFacturacionCompraVentaSIN.ServicioFacturacion.recepcionFactura(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionFactura request) {
            return base.Channel.recepcionFactura(request);
        }
        
        public PryCertificaSIN.ServiceFacturacionCompraVentaSIN.respuestaRecepcion recepcionFactura(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.solicitudRecepcionFactura SolicitudServicioRecepcionFactura) {
            PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionFactura inValue = new PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionFactura();
            inValue.SolicitudServicioRecepcionFactura = SolicitudServicioRecepcionFactura;
            PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionFacturaResponse retVal = ((PryCertificaSIN.ServiceFacturacionCompraVentaSIN.ServicioFacturacion)(this)).recepcionFactura(inValue);
            return retVal.RespuestaServicioFacturacion;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionFacturaResponse> PryCertificaSIN.ServiceFacturacionCompraVentaSIN.ServicioFacturacion.recepcionFacturaAsync(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionFactura request) {
            return base.Channel.recepcionFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionFacturaResponse> recepcionFacturaAsync(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.solicitudRecepcionFactura SolicitudServicioRecepcionFactura) {
            PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionFactura inValue = new PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionFactura();
            inValue.SolicitudServicioRecepcionFactura = SolicitudServicioRecepcionFactura;
            return ((PryCertificaSIN.ServiceFacturacionCompraVentaSIN.ServicioFacturacion)(this)).recepcionFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PryCertificaSIN.ServiceFacturacionCompraVentaSIN.validacionRecepcionMasivaFacturaResponse PryCertificaSIN.ServiceFacturacionCompraVentaSIN.ServicioFacturacion.validacionRecepcionMasivaFactura(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.validacionRecepcionMasivaFactura request) {
            return base.Channel.validacionRecepcionMasivaFactura(request);
        }
        
        public PryCertificaSIN.ServiceFacturacionCompraVentaSIN.respuestaRecepcion validacionRecepcionMasivaFactura(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.solicitudValidacionRecepcion SolicitudServicioValidacionRecepcionMasiva) {
            PryCertificaSIN.ServiceFacturacionCompraVentaSIN.validacionRecepcionMasivaFactura inValue = new PryCertificaSIN.ServiceFacturacionCompraVentaSIN.validacionRecepcionMasivaFactura();
            inValue.SolicitudServicioValidacionRecepcionMasiva = SolicitudServicioValidacionRecepcionMasiva;
            PryCertificaSIN.ServiceFacturacionCompraVentaSIN.validacionRecepcionMasivaFacturaResponse retVal = ((PryCertificaSIN.ServiceFacturacionCompraVentaSIN.ServicioFacturacion)(this)).validacionRecepcionMasivaFactura(inValue);
            return retVal.RespuestaServicioFacturacion;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PryCertificaSIN.ServiceFacturacionCompraVentaSIN.validacionRecepcionMasivaFacturaResponse> PryCertificaSIN.ServiceFacturacionCompraVentaSIN.ServicioFacturacion.validacionRecepcionMasivaFacturaAsync(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.validacionRecepcionMasivaFactura request) {
            return base.Channel.validacionRecepcionMasivaFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<PryCertificaSIN.ServiceFacturacionCompraVentaSIN.validacionRecepcionMasivaFacturaResponse> validacionRecepcionMasivaFacturaAsync(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.solicitudValidacionRecepcion SolicitudServicioValidacionRecepcionMasiva) {
            PryCertificaSIN.ServiceFacturacionCompraVentaSIN.validacionRecepcionMasivaFactura inValue = new PryCertificaSIN.ServiceFacturacionCompraVentaSIN.validacionRecepcionMasivaFactura();
            inValue.SolicitudServicioValidacionRecepcionMasiva = SolicitudServicioValidacionRecepcionMasiva;
            return ((PryCertificaSIN.ServiceFacturacionCompraVentaSIN.ServicioFacturacion)(this)).validacionRecepcionMasivaFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionAnexosResponse PryCertificaSIN.ServiceFacturacionCompraVentaSIN.ServicioFacturacion.recepcionAnexos(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionAnexos request) {
            return base.Channel.recepcionAnexos(request);
        }
        
        public PryCertificaSIN.ServiceFacturacionCompraVentaSIN.respuestaRecepcion recepcionAnexos(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.solicitudRecepcionAnexos SolicitudRecepcionAnexos) {
            PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionAnexos inValue = new PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionAnexos();
            inValue.SolicitudRecepcionAnexos = SolicitudRecepcionAnexos;
            PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionAnexosResponse retVal = ((PryCertificaSIN.ServiceFacturacionCompraVentaSIN.ServicioFacturacion)(this)).recepcionAnexos(inValue);
            return retVal.RespuestaRecepcionAnexos;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionAnexosResponse> PryCertificaSIN.ServiceFacturacionCompraVentaSIN.ServicioFacturacion.recepcionAnexosAsync(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionAnexos request) {
            return base.Channel.recepcionAnexosAsync(request);
        }
        
        public System.Threading.Tasks.Task<PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionAnexosResponse> recepcionAnexosAsync(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.solicitudRecepcionAnexos SolicitudRecepcionAnexos) {
            PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionAnexos inValue = new PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionAnexos();
            inValue.SolicitudRecepcionAnexos = SolicitudRecepcionAnexos;
            return ((PryCertificaSIN.ServiceFacturacionCompraVentaSIN.ServicioFacturacion)(this)).recepcionAnexosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionMasivaFacturaResponse PryCertificaSIN.ServiceFacturacionCompraVentaSIN.ServicioFacturacion.recepcionMasivaFactura(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionMasivaFactura request) {
            return base.Channel.recepcionMasivaFactura(request);
        }
        
        public PryCertificaSIN.ServiceFacturacionCompraVentaSIN.respuestaRecepcion recepcionMasivaFactura(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.solicitudRecepcionMasiva SolicitudServicioRecepcionMasiva) {
            PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionMasivaFactura inValue = new PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionMasivaFactura();
            inValue.SolicitudServicioRecepcionMasiva = SolicitudServicioRecepcionMasiva;
            PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionMasivaFacturaResponse retVal = ((PryCertificaSIN.ServiceFacturacionCompraVentaSIN.ServicioFacturacion)(this)).recepcionMasivaFactura(inValue);
            return retVal.RespuestaServicioFacturacion;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionMasivaFacturaResponse> PryCertificaSIN.ServiceFacturacionCompraVentaSIN.ServicioFacturacion.recepcionMasivaFacturaAsync(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionMasivaFactura request) {
            return base.Channel.recepcionMasivaFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionMasivaFacturaResponse> recepcionMasivaFacturaAsync(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.solicitudRecepcionMasiva SolicitudServicioRecepcionMasiva) {
            PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionMasivaFactura inValue = new PryCertificaSIN.ServiceFacturacionCompraVentaSIN.recepcionMasivaFactura();
            inValue.SolicitudServicioRecepcionMasiva = SolicitudServicioRecepcionMasiva;
            return ((PryCertificaSIN.ServiceFacturacionCompraVentaSIN.ServicioFacturacion)(this)).recepcionMasivaFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PryCertificaSIN.ServiceFacturacionCompraVentaSIN.verificacionEstadoFacturaResponse PryCertificaSIN.ServiceFacturacionCompraVentaSIN.ServicioFacturacion.verificacionEstadoFactura(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.verificacionEstadoFactura request) {
            return base.Channel.verificacionEstadoFactura(request);
        }
        
        public PryCertificaSIN.ServiceFacturacionCompraVentaSIN.respuestaRecepcion verificacionEstadoFactura(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.solicitudVerificacionEstado SolicitudServicioVerificacionEstadoFactura) {
            PryCertificaSIN.ServiceFacturacionCompraVentaSIN.verificacionEstadoFactura inValue = new PryCertificaSIN.ServiceFacturacionCompraVentaSIN.verificacionEstadoFactura();
            inValue.SolicitudServicioVerificacionEstadoFactura = SolicitudServicioVerificacionEstadoFactura;
            PryCertificaSIN.ServiceFacturacionCompraVentaSIN.verificacionEstadoFacturaResponse retVal = ((PryCertificaSIN.ServiceFacturacionCompraVentaSIN.ServicioFacturacion)(this)).verificacionEstadoFactura(inValue);
            return retVal.RespuestaServicioFacturacion;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PryCertificaSIN.ServiceFacturacionCompraVentaSIN.verificacionEstadoFacturaResponse> PryCertificaSIN.ServiceFacturacionCompraVentaSIN.ServicioFacturacion.verificacionEstadoFacturaAsync(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.verificacionEstadoFactura request) {
            return base.Channel.verificacionEstadoFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<PryCertificaSIN.ServiceFacturacionCompraVentaSIN.verificacionEstadoFacturaResponse> verificacionEstadoFacturaAsync(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.solicitudVerificacionEstado SolicitudServicioVerificacionEstadoFactura) {
            PryCertificaSIN.ServiceFacturacionCompraVentaSIN.verificacionEstadoFactura inValue = new PryCertificaSIN.ServiceFacturacionCompraVentaSIN.verificacionEstadoFactura();
            inValue.SolicitudServicioVerificacionEstadoFactura = SolicitudServicioVerificacionEstadoFactura;
            return ((PryCertificaSIN.ServiceFacturacionCompraVentaSIN.ServicioFacturacion)(this)).verificacionEstadoFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PryCertificaSIN.ServiceFacturacionCompraVentaSIN.validacionRecepcionPaqueteFacturaResponse PryCertificaSIN.ServiceFacturacionCompraVentaSIN.ServicioFacturacion.validacionRecepcionPaqueteFactura(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.validacionRecepcionPaqueteFactura request) {
            return base.Channel.validacionRecepcionPaqueteFactura(request);
        }
        
        public PryCertificaSIN.ServiceFacturacionCompraVentaSIN.respuestaRecepcion validacionRecepcionPaqueteFactura(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.solicitudValidacionRecepcion SolicitudServicioValidacionRecepcionPaquete) {
            PryCertificaSIN.ServiceFacturacionCompraVentaSIN.validacionRecepcionPaqueteFactura inValue = new PryCertificaSIN.ServiceFacturacionCompraVentaSIN.validacionRecepcionPaqueteFactura();
            inValue.SolicitudServicioValidacionRecepcionPaquete = SolicitudServicioValidacionRecepcionPaquete;
            PryCertificaSIN.ServiceFacturacionCompraVentaSIN.validacionRecepcionPaqueteFacturaResponse retVal = ((PryCertificaSIN.ServiceFacturacionCompraVentaSIN.ServicioFacturacion)(this)).validacionRecepcionPaqueteFactura(inValue);
            return retVal.RespuestaServicioFacturacion;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PryCertificaSIN.ServiceFacturacionCompraVentaSIN.validacionRecepcionPaqueteFacturaResponse> PryCertificaSIN.ServiceFacturacionCompraVentaSIN.ServicioFacturacion.validacionRecepcionPaqueteFacturaAsync(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.validacionRecepcionPaqueteFactura request) {
            return base.Channel.validacionRecepcionPaqueteFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<PryCertificaSIN.ServiceFacturacionCompraVentaSIN.validacionRecepcionPaqueteFacturaResponse> validacionRecepcionPaqueteFacturaAsync(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.solicitudValidacionRecepcion SolicitudServicioValidacionRecepcionPaquete) {
            PryCertificaSIN.ServiceFacturacionCompraVentaSIN.validacionRecepcionPaqueteFactura inValue = new PryCertificaSIN.ServiceFacturacionCompraVentaSIN.validacionRecepcionPaqueteFactura();
            inValue.SolicitudServicioValidacionRecepcionPaquete = SolicitudServicioValidacionRecepcionPaquete;
            return ((PryCertificaSIN.ServiceFacturacionCompraVentaSIN.ServicioFacturacion)(this)).validacionRecepcionPaqueteFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PryCertificaSIN.ServiceFacturacionCompraVentaSIN.anulacionFacturaResponse PryCertificaSIN.ServiceFacturacionCompraVentaSIN.ServicioFacturacion.anulacionFactura(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.anulacionFactura request) {
            return base.Channel.anulacionFactura(request);
        }
        
        public PryCertificaSIN.ServiceFacturacionCompraVentaSIN.respuestaRecepcion anulacionFactura(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.solicitudAnulacion SolicitudServicioAnulacionFactura) {
            PryCertificaSIN.ServiceFacturacionCompraVentaSIN.anulacionFactura inValue = new PryCertificaSIN.ServiceFacturacionCompraVentaSIN.anulacionFactura();
            inValue.SolicitudServicioAnulacionFactura = SolicitudServicioAnulacionFactura;
            PryCertificaSIN.ServiceFacturacionCompraVentaSIN.anulacionFacturaResponse retVal = ((PryCertificaSIN.ServiceFacturacionCompraVentaSIN.ServicioFacturacion)(this)).anulacionFactura(inValue);
            return retVal.RespuestaServicioFacturacion;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PryCertificaSIN.ServiceFacturacionCompraVentaSIN.anulacionFacturaResponse> PryCertificaSIN.ServiceFacturacionCompraVentaSIN.ServicioFacturacion.anulacionFacturaAsync(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.anulacionFactura request) {
            return base.Channel.anulacionFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<PryCertificaSIN.ServiceFacturacionCompraVentaSIN.anulacionFacturaResponse> anulacionFacturaAsync(PryCertificaSIN.ServiceFacturacionCompraVentaSIN.solicitudAnulacion SolicitudServicioAnulacionFactura) {
            PryCertificaSIN.ServiceFacturacionCompraVentaSIN.anulacionFactura inValue = new PryCertificaSIN.ServiceFacturacionCompraVentaSIN.anulacionFactura();
            inValue.SolicitudServicioAnulacionFactura = SolicitudServicioAnulacionFactura;
            return ((PryCertificaSIN.ServiceFacturacionCompraVentaSIN.ServicioFacturacion)(this)).anulacionFacturaAsync(inValue);
        }
    }
}
